name: Build & Deploy Storybook
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and Deploy
        run: |
          npm install
          npm run deploy-storybook -- --ci --source-branch=${{ GITHUB_REF_NAME }}
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}